### ISSUE TITLE
all authors in side menu

### ISSUE THREAD

**Issue by LukasCBossert** [monperrus/bibtexbrowser#102]
Is there a way to get all authors into one menu page (with a scroll down bar), so there is no need for clicking through several pages?

**Comment by monperrus** [comment]
This is already supported: https://www.monperrus.net/martin/bibtexbrowser.php?frameset&bib=monperrus.bib

**Comment by LukasCBossert** [comment]
great - but what do I have to write into the `bibtexbrowser.local.php` ? How do I get the menu with the keywords?

**Comment by monperrus** [comment]
in Wordpress and in direct Bibtexbrowser?

**Comment by LukasCBossert** [comment]
since I just found out how to use the bibtexbrowser properly I won't use the WP-Plugin, so for me I am curious how it works for direct Bibtexbrowser.

**Comment by monperrus** [comment]
All menus are present by default, without `bibtexbrowser.local.php`

**Comment by LukasCBossert** [comment]
Right. And with `@define('AUTHORS_SIZE',30); // number of authors per table` one can change the length of the side menu.
