### ISSUE TITLE
keyword with parentheses will not redirect to bibtex-entry

### ISSUE THREAD

**Issue by LukasCBossert** [monperrus/bibtexbrowser#103]
When parentheses `()`appear in the field `keywords`, the keyword is listed in the side menu, but clicking on it does not lead to the landing page of the bibtey-entry.

Instead the website says 
> Sorry, no results for this query

**Comment by monperrus** [comment]
Thanks for the bug report. This should be easy to fix (add `urlencode` somehwere). Would you give it a try?

**Comment by LukasCBossert** [comment]
sorry for asking, but where exactly should I add `urlencode` somewhere? in `bibtexbrowser.local.php`? Just `urlencode` within `<?php ...?>`?

**Comment by monperrus** [comment]
On my machine, keywords with parentheses work with valid links. 

Plus `urlencode` is already applied, see https://github.com/monperrus/bibtexbrowser/blob/f48e78d/bibtexbrowser.php#L2615

The bug may come from your PHP or webserver config (Apache?)

**Comment by LukasCBossert** [comment]
ok - thanks. I have bibtexbrowser running on www.crc1382.texografie.de, no idea about the Apache configuration, nevermind, I found a workaround replace `()` with `❬❭` which is sufficient right now.
