### ISSUE TITLE
Filtering by author is sensitive to the format of the author field

### ISSUE THREAD

**Issue by sergey-goncharov** [monperrus/bibtexbrowser#106]
I am migrating from v20111211 to the current one, and previously this issue was not present, which indicates to me that it might be a regression. 

The filter `$_GET['author']='Sergey Goncharov';` used to include both the entries with 'Sergey Goncharov' as an author and 'Goncharov, Sergey'. The latter option is no longer covered. However, `$_GET['author']='Goncharov, Sergey';` would cover this, but then only this option.

**Comment by monperrus** [comment]
Thanks for the bug report.

There has been some work on this part.

Can you try with `_author` instead, `$_GET['author']='Sergey Goncharov';`?

(see `Q_INNER_AUTHOR` in code)

**Comment by sergey-goncharov** [comment]
Sorry, maybe I was not clear enough. I am trying to use the following scenario from the documentation (which used to function): 

```
<?php $_GET['bib']='mybib.bib'; 
$_GET['author']='Martin Monperrus'; 
include( 'bibtexbrowser.php' ); ?>
```
And that brings up the issue I've described. Are you implying that there is something I should use instead of `$_GET['author']='Martin Monperrus'; ` now?

**Comment by monperrus** [comment]
yes, please try, it may fix your usage.

**Comment by sergey-goncharov** [comment]
I've tried some variations of `$_GET['author']='Sergey Goncharov';` (including `$_GET['_author']='Sergey Goncharov';` -- this just shows the whole list of publications, not only mine). I also tried to form a direct url-request. No, it did not help. Maybe there is a way to show the whole generated database e.g. as XML? That would help in debugging quite a bit.
