### ISSUE TITLE
Function Deparated Message

### ISSUE THREAD

**Issue by babaks77** [monperrus/bibtexbrowser#109]
I'm not entirely sure what PHP configuration my university uses (but I assume it is up to date). I'm getting this warning/error message: 

`Deprecated: Function get_magic_quotes_runtime() is deprecated in /groups/qdyn/web/_php/bibtexbrowser.php on line 310`

However, it seems the output is generated otherwise without a problem.

**Comment by monperrus** [comment]
Thanks for the bug report. Does https://github.com/monperrus/bibtexbrowser/pull/110 fix the problem?

**Comment by babaks77** [comment]
So basically remove that check? Yes, I think that's what I did and that works for my version of PHP (now determined to be 7.4).

**Comment by monperrus** [comment]
Thanks
