### ISSUE TITLE
Text of JavaScript code appearing in the output

### ISSUE THREAD

**Issue by silarri** [monperrus/bibtexbrowser#118]
If I format an entry with "&astext" (e.g., http://webdiis.unizar.es/~silarri/bibtexbrowser.php?bib=pubs.bib&search=sncs2022&astext), I can see in the output some JavaScript code. I think that this did not appear before. Any ideas about how to solve this problem are welcome. Thank you very much.

**Comment by monperrus** [comment]
Can you try to add into bibtexbrowser.local.php:

    <?php
    define('BIBTEXBROWSER_USE_PROGRESSIVE_ENHANCEMENT',false);
    ?>

**Comment by silarri** [comment]
Thanks a lot! This seems to solve the problem. I had that defined in bibtexbrowser.local with @define, but it seems that it was not working like that.

**Comment by monperrus** [comment]
Cool!
