### ISSUE TITLE
Note field in bibtex entry not shown

### ISSUE THREAD

**Issue by silarri** [monperrus/bibtexbrowser#131]
I cannot managed to get "note" fields in the bibtex entries to be shown when using bibtexbrowser. They are not shown even for @misc entries. If there is any way to force the appearance of this field, it would be very nice to know. I tried modifying the .css field, but I did not succeed.

**Comment by monperrus** [comment]
by default, notes are filtered out. To fix this, add in `bibtexbrowser.local.php`

```
@define('BIBTEXBROWSER_BIBTEX_VIEW_FILTEREDOUT','comment|file');
```

**Comment by monperrus** [comment]
could you give an example of a bibtex entry and the expected output?

**Comment by silarri** [comment]
Sorry for the delay, I didn't see the answer. Here there is an example of bibtex entry:

@inproceedings{exampleEntry,
  author = {Aurora Macías and Elena Navarro and Carlos E. Cuesta and Uwe Zdun},
  title = {Architecting Digital Twins Using a Domain-Driven Design-Based Approach},
  booktitle = {XXVII Jornadas de Ingenier\'{\i}a del Software y Bases de Datos (JISBD 2023)},
  month = {September},
  note = {handle: 11705/JISBD/2023/7321},
  year = {2023},
  url = {https://hdl.handle.net/11705/JISBD/2023/7321},
  month = {September},
  pages = {1--1},
  publisher = {SISTEDES},
  editor = {Amador Dur\'{a}n Toro},
}

In the expected output, the text in the note field (i.e., "handle: 11705/JISBD/2023/7321") should appear, but I cannot see that text.

Any help is welcome!

**Comment by monperrus** [comment]
thanks, fixed in the latest commit.

**Comment by silarri** [comment]
I replaced the previous bibtexbrowser.php file with the new one, but then I get no output at all in the web page (no publications are shown). Maybe there was some change that requires a modification of the configuration of the system?

**Comment by monperrus** [comment]
yes, but I don't know which one.

**Comment by silarri** [comment]
After careful revision, my problem was that the PHP version of the server was slightly older than 5.4.0. To solve it, I had to perform some changes in the code:

In line 4073 I had to change:

$names = [];
by:
$names = array();

At the beginning of the code, I had to add:

if (!defined('ENT_XHTML')) {
    define('ENT_XHTML', 32); // Value of ENT_XHTML in PHP 5.4.0
}

if (!defined('PHP_INT_MIN')) {
    define('PHP_INT_MIN', ~PHP_INT_MAX); // Complement of PHP_INT_MAX
}

**Comment by monperrus** [comment]
thanks for the update.
