### ISSUE TITLE
Error/warning when running on PHP 8.3

### ISSUE THREAD

**Issue by babaks-git** [monperrus/bibtexbrowser#133]
PHP 8.3 issues the following errors/warnings:

- Deprecated: Creation of dynamic property AcademicDisplay::$entries is deprecated in [...]bibtexbrowser.php on line 3342
- Deprecated: Creation of dynamic property AcademicDisplay::$title is deprecated in [...]bibtexbrowser.php on line 3334
- Deprecated: Creation of dynamic property AcademicDisplay::$db is deprecated in [...]bibtexbrowser.php on line 3362

I use it without issues on PHP 8.2 [here](https://qdyn.physics.indiana.edu/publications/index.html), but we are preparing to upgrade PHP. Despite the error messages, the output on PHP 8.3 looks fine to me, but the messages show up at the top of the page. Not a nice first impression!

I guess I can hack my way (as usual) to fixing the code, but if anyone has a solution already to update the code to be compatible with PHP 8.3 I'd appreciate it.

**Comment by monperrus** [comment]
Thanks for the bug report @babaks-git. Could you try again with the [latest version](https://raw.githubusercontent.com/monperrus/bibtexbrowser/master/bibtexbrowser.php)?

**Comment by monperrus** [comment]
fixed in master
