### ISSUE TITLE
online demo: render bib files from github

### ISSUE THREAD

**Issue by thorade** [monperrus/bibtexbrowser#24]
Just an idea: 
From the project homepage
http://www.monperrus.net/martin/bibtexbrowser/
you are linking to an online demo:
http://my.publications.li/

Could you extend that online demo in a way that it accepts bib files from github?
Like this one:
https://github.com/CoolProp/CoolProp/blob/master/CoolPropBibTeXLibrary.bib
Reading a rendered version would be a lot nicer than reading the raw file.

**Comment by monperrus** [comment]
Hi,
Thanks for the suggestion. However, http://my.publications.li/ is in end-of-life mode. It will be shut down on March 31. --Martin
