### ISSUE TITLE
Title not preserved after application of filter

### ISSUE THREAD

**Issue by paxperscientiam** [monperrus/bibtexbrowser#29]
Hi there, monperrus, we communicated a while ago when I suggested that there should be a way to construct a URL for loading up an entire bibliography.

1)
I recently noticed that the title of the bibliography is replaced with the current filter once one has been chosen. Would it be possible to introduce a third descriptive line for the heading of the main window?
Something like this:
• Title of bibliography
• Current filter
• Results

2)
What about giving the web user the ability to select simultaneous filters?
• Type+Year+Author
• Type+Year
• Type+Author
• Any number of types
• any number of authors
• any number of years

The second item might be asking for the moon, but I think at the very least tweaking things according to the first item would be a great improvement on what is already a stellar product.

**Comment by monperrus** [comment]
> What about giving the web user the ability to select simultaneous filters?
This is already supported, eg `?title=foo&year=2014`

Best, --Martin

**Comment by monperrus** [comment]
> 1)
> I recently noticed that the title of the bibliography is replaced with
> the current filter once one has been chosen. Would it be possible to
> introduce a third descriptive line for the heading of the main window?
> Something like this:
> • Title of bibliography
What string would be taken as title?

**Comment by paxperscientiam** [comment]
Hi monperrus , sorry if I wasn't very clear.

From what I can tell, the default behavior is to set the bibliography title to that of the bib file name. So, if the file is called pax-library.bib, then the bibliography title rendered by bibtexbrowser is "Publications in pax-library.bib".

Quick aside -- is there currently no way to define a custom title within bibtexbrowser.local.php?

Seems like this would contribute to solving two problems: user gets a custom bibliography title independent of the file name and that title gets its own dedicated header line...or something.

So, instead of the (default or custom) title being replaced once the user has chosen a filter, the search results are headed by both the (default or custom) title *and* the current filter.


Sorry, when I said "user", I meant "end user" -- as in a visitor. Sure, I as the creator of the website could construct such URL's, but it's not user-friendly enough for an "end-user." Besides, something like "?title=foo&year=2014" gets rid of the nice side panel controls.


From a UX point of view, this could be done by making each filter a toggle: a toggle approach would give the end-user the ability to choose any combination of "types," "authors," "years," etc.

**Comment by monperrus** [comment]
> Quick aside -- is there currently no way to define a custom title
> within bibtexbrowser.local.php?
>
Not yet, I will add this feature

**Comment by monperrus** [comment]
> From a UX point of view, this could be done by making each filter a
> toggle: a toggle approach would give the end-user the ability to
> choose any combination of "types," "authors," "years," etc.
>
Do you mean a kind of faceted search from the left-hand side menu?

**Comment by monperrus** [comment]
Added a way to tweak the title, see section 'How to use the change the title of the result page?' in the documentation.

**Comment by paxperscientiam** [comment]
Nice work, monperrus. The title alteration works perfectly! Thanks :)

> Do you mean a kind of faceted search from the left-hand side menu?
Yes, I think we're on nearly the same page. Perhaps a "clear all filters" option; a "clear types filters"; "clear years filters," etc.
Rather than using toggle "switches" for individual filters, the existing filter links could be toggled merely by clicking on them. There, of course, would need to be a visual aid to indicate to the end-user whether a toggle is active or inactive.

**Comment by monperrus** [comment]
Could you open a new issue for the faceted search?

--Martin
