### ISSUE TITLE
Invalid argument supplied for foreach...

### ISSUE THREAD

**Issue by paxperscientiam** [monperrus/bibtexbrowser#32]
So, I started getting this error recently. For reference, I'm using the bleeding edge version of bibtexbrowser off of GitHub.

The error reads something like this:
> Invalid argument supplied for foreach...line 3685

I think it was line 3685...
The code on the line is this...
> foreach($metatags as $item) {

I found that changing that line to this remedied the issue...
> foreach((array) $metatags as $item) {

I can't say whether or not this is the answer as I don't fully understand the problem, but it does appear to solve the problem.

So, yeah.

**Comment by monperrus** [comment]
What is your PHP version?

--Martin

**Comment by paxperscientiam** [comment]
Hey Martin, I'm running PHP 5.6.9 locally and PHP 5.6.5 on my web host.

**Comment by monperrus** [comment]
just fixed the bug, see 120ca1da219a7b9169884a5b99b00296d3931fca
