### ISSUE TITLE
Sample code for publication pages

### ISSUE THREAD

**Issue by i2000s** [monperrus/bibtexbrowser#38]
Hi Bibtexbrowser developers,

I would like to use the tool for my research group's website. However, I found it difficult to embed the code given on the bibtexbrowser website to my WordPress pages. The php code 
```
<?php $_GET['bib']='/faux/bibtex.bib';
 $_GET['author']=authorname;
 include( '/faux/bibtexbrowser.php' );
 ?> 
```
simply does not work if I embed it on one WP page. On the other hand, the link
```
<a href="/faux/bibtexbrowser.php?bib=bibtex.bib&search=authorname&academic" target="_blank">Test Link</a>.
```
works but I am not sure how to list publications from many authors and how to make the publication page look like [this one](http://telin.ugent.be/~akumcu/ipi-publications/bibtexbrowser.php?frameset&bib=IPI-A1.bib;IPI-C1.bib;IPI-C3.bib;IPI-P1.bib;philips-A1.bib;philips-A2.bib;philips-A4.bib;philipsbooks.bib;philips-C1.bib;philips-C3.bib;philips-P1.bib).

I am not a php expert as many researchers do, but if there are many code samples and templates for practical usage of the great tool, that would be excellent!

Thanks,
Qi

**Comment by monperrus** [comment]
Have a look at https://wordpress.org/plugins/wp-publications/ which integrates bibtexbrowser with Wordpress

**Comment by i2000s** [comment]
Yes, I know this plugin. But I am trying to customizing your php code and embed it into a wordpress website without using the plugin. If more details of installing and customizing it can be shared, that would be great. I think I will figure it out. Just my two cents. Thanks.

**Comment by i2000s** [comment]
@monperrus Do you know if it is possible to use this tool to make a submission form for internal group members to submit their publication online and show the publication list with some internal information like grant number, publication group tags associated to each publication as a tex&pdf file to group member only? The internal info should not be shown to the public and everyone in the group should be able to submit their publications without digging into the bibtex library. I am using the Ultimate Member plugin in Wordpress to let users register into different groups on our website. Any guideline would be helpful. This may be also useful for other bibtexbrowser users. Thank you again.

**Comment by monperrus** [comment]
> Do you know if it is possible to use this tool to make a submission form for internal group members to submit their publication online

Any upload tool would work, such as OwnCloud

> show the publication list with some internal information like grant number, publication group tags associated to each publication as a tex

This can be done for instance using the `keyword` search parameter that searches in the `keywords` bibtex entry.

Best, --Martin

**Comment by i2000s** [comment]
Just a followup from a comment on your website. I appreciate if you guide me to make a page template to list the search result of publications. 

On my Wordpress site, I defined a short code to generate a publication list with a search form using the following code as a shortcode generator:
```
function cquic_biblib_func( $atts, $content = null ) {
    $a = shortcode_atts( array(
        'bib' => 'lib.bib',
        'authors' => 'all'
        ), $atts );
              
	$_GET['academic']=1;
	$_GET['bib']=$a['bib'];
	if ($a['authors'] == 'all') {
		$_GET['all']=1;
	} else {
		$_GET['author']=$a['authors'];
	}
	echo '
	<form action="/bibtexbrowser.php?" method="get" target="main">
	<div class="sortbox toolbox">
            <div class="search">
            	<input type="text" name="search" class="input_box" id="searchtext"/>
            	<input type="hidden" name="bib" value="lib.bib"/>
            	<input type="submit" value="search" class="input_box"/>
            </div>
        </div>
	</form>';
	include( 'bibtexbrowser.php' );

	// setDB();
      	// new Dispatcher();
}

add_shortcode('cquic_biblib', 'cquic_biblib_func');
```
Then in the `bibtexbrowser.local.php` code, I define the following customized template for the page opened to show search result:
```
<?php
define('BIBTEXBROWSER_DEFAULT_TEMPLATE','CustomHTMLTemplate');

function CustomHTMLTemplate(&$content) {
        require( 'wp-blog-header.php');
       include ( TEMPLATEPATH . '/content.php');
        echo '<div id="bodyText">';      
          $content->display();      
        echo '</div>';
   } 
?>
```
Certainly, I have other customized content in the local file. I expect that when I search a keyword in the search bar (see [here](http://cquic.unm.edu/research/cquic-publications/)), the newly opened page should have the header and footer defined in my template page. But it does not. There are also warnings saying that 
```
Warning: Cannot modify header information - headers already sent by (output started at /home/cquic/public_html/bibtexbrowser.local.php:144) in /home/cquic/public_html/bibtexbrowser.php on line 3832
 
Warning: Invalid argument supplied for foreach() in /home/cquic/public_html/bibtexbrowser.php on line 3851
```
Actually, I am not sure how can I define the html template using your tool. Could you illustrate me some tricks? Thanks.
