### ISSUE TITLE
BIBTEX link

### ISSUE THREAD

**Issue by i2000s** [monperrus/bibtexbrowser#39]
Hi Martin,

I am embedding this wonderful tool to a research group website, but I found the ***[bibtex]*** does not link to a correct location. For example, if you look into [a test page](http://cquic.unm.edu/faux/deutschs-group/publications/), the link on each ***[bibtex]*** is using a relative address of the page. However, since the bibtexbrowser.php file is located at the root directory of the test site not the page directory, the correct link should be relative to the root directory of the site. To show the effect using a correct url, I have made [a test page on the root directory](http://cquic.unm.edu/faux/bibtexbrowser.php?bib=CQuICmembers.bib&search=Deutsch|Baragiola|Baldwin|Qi|Shojaee|Kalev&academic), in which the ***[bibtex]*** actually works as expected. 

I tried to modify the `getBibLink()` and `getURL()` functions in your code to fix this problem, but obviously I don't have the knowledge on how to use the url where the `bibtexbrowser.php` is. Can you help me fix this problem? I guess this problem maybe common for other people as well. Thanks.

**Comment by monperrus** [comment]
Do you use wp-publications or bibtexbrowser directly?

**Comment by i2000s** [comment]
I use bibtexbrowser.php directly for customizing an interface and MySQL database purpose.

**Comment by monperrus** [comment]
> I tried to modify the getBibLink() and getURL() functions in your code to fix this problem

It looks like a good option. What are your changes?

**Comment by i2000s** [comment]
I have tried to replace line 1148 of the bibtexbrowser.php in the `getBibLink()` function to be
```
$href = 'href="'.$this->basename($_SERVER['bibtexbrowser'],'.php').'"';
```
The idea is to find the URL of the current bibtexbrowser.php file, and has referenced to [this post](http://stackoverflow.com/questions/13200339/how-do-you-recieve-your-current-php-file-url), but it does not work. The error message is 
```
Fatal error: Call to undefined method BibEntry::basename() in /home/cquic/public_html/faux/bibtexbrowser.php on line 1149
```
Obviously, I have ignored the parameters and so on. 

How to do it currently? Also, I am testing to include the arXiv link to the list, which would be another issue.

**Comment by i2000s** [comment]
Ok, I tried replacing line 192 to 
```
@define('BIBTEXBROWSER_URL',basename($_SERVER['bibtexbrowser'],'.php')); 
```
It seems works, but the output bibtex information has the URL line wrongly including incomplete information there...

**Comment by monperrus** [comment]
> It seems works, but the output bibtex information has the URL line wrongly including incomplete information there... 

What is in the incomplete information?

> Update: with a quick fix, the URL is actually replaced by the DOI link.

Cool. What is the quick fix?

**Comment by i2000s** [comment]
The quick fix is the line I changed on the last post. The output is shown in issue #40. Thanks for checking it.
