### ISSUE TITLE
Cannot show correctly for URLs 

### ISSUE THREAD

**Issue by i2000s** [monperrus/bibtexbrowser#40]
As I was rewriting some codes in the bibtexbrowser.php file to solve the bibtex link problem discussed in #39, I found URLs with dots/periods in the url cannot be shown correctly. For example, if I click the ***[bibtex]*** link under a bibtex entry, there shows the following bibtex info:
```
@Article{Baldwin2014Quantum,
  Title                    = {Quantum process tomography of unitary and near-unitary maps},
  Author                   = {Baldwin, Charles H. and Kalev, Amir and Deutsch, Ivan H.},
  Journal                  = {Phys. Rev. A},
  Year                     = {2014},

  Month                    = {Jul},
  Pages                    = {012110},
  Volume                   = {90},

  Arxiv                    = {1404.2877},
  Doi                      = {10.1103/PhysRevA.90.012110},
  Gsid                     = {13589829371783546640},
  Issue                    = {1},
  Numpages                 = {10},
  Publisher                = {American Physical Society},
  Timestamp                = {2015.09.09},
  Url                      = {10.1103/PhysRevA.90.012110">http://link.aps.org/doi/10.1103/PhysRevA.90.012110}
}
```
Notice that the ***Url*** entry has a value looking strange. Obviously, it uses the URL address for the pdf entry, while having the incompleted `10.1103/PhysRevA.90.012110">` as a part of the `<a href="http://link.aps.org/doi/10.1103/PhysRevA.90.012110">...</a>`. 

Should this bug be fixed easily? Thanks.

**Comment by i2000s** [comment]
I think this occurs when the `doi` field is also a part of the `url` field. So, in function `toEntryUnformatted()`, it searches the `url` field and replaced with a hyperlink, and then the function searches the `doi` field and replace the keywords both in the current `url` link and `doi` field text with the link code. In the end, the searching string and then replacing with a link strategy messed up the bibtex code in output... 

A quick fix is to switch the order of `url` and `doi` and others in the `$hyperlinks` array. Could it be better to limit the replacement operation only to the corresponding field where the text will be linked to a URL address?  Thanks.

**Comment by monperrus** [comment]
Looking at `Url = {10.1103/PhysRevA.90.012110">http://link.aps.org/doi/10.1103/PhysRevA.90.012110}`.

Is it the original bibtex field? or the one output by bibtexbrowser?

**Comment by i2000s** [comment]
That's the output from bibtexbrowser. The original one should be 
```
Url                      = {http://link.aps.org/doi/10.1103/PhysRevA.90.012110}
```

**Comment by monperrus** [comment]
could you try the latest version?

**Comment by i2000s** [comment]
That works! See [here](http://cquic.unm.edu/research/cquic-publications/). Thanks.

BTW, I added the arXiv entry in my forked master branch. Feel free to merge to your master branch, if you think it is useful.

**Comment by monperrus** [comment]
> I added the arXiv entry in my forked master branch

Excellent. Could you create a pull request with this change only?

**Comment by i2000s** [comment]
I will do it when I got a chance later...
