### ISSUE TITLE
Embed the search page

### ISSUE THREAD

**Issue by i2000s** [monperrus/bibtexbrowser#43]
Hi,

I think it would be nice to allow the output of the search results to be embedded in the page. Maybe the code has already allow to do so, but I just don't know how. Could you shed a light on this? Thanks.

Regards,
Qi

**Comment by monperrus** [comment]
Already doable:

    <?php 
    $_GET['bib']='csgroup2008.bib';
    $_GET['search']='foo';
    include( 'bibtexbrowser.php' );
    ?>
