### ISSUE TITLE
Synchronize/Feed MySQL database to the bibtex file

### ISSUE THREAD

**Issue by i2000s** [monperrus/bibtexbrowser#44]
I think it would be nice if the code can let user decide if they want to feed and synchronize a MySQL database to the bibtex file. Since we have already had a code to feed the bibtex data to a MySQL database (see [here](https://gist.github.com/i2000s/0cb40e8bb8a291b4f082) for my updated version), I feel it might be possible to reverse the process -- feed MySQL database to the bibtex file and synchronize them when there is a change on either side. Once this is done, then it is possible to make plugins to submit new publications through an online form while the MySQL data entries can also be used for other advanced development as well. 

Hope this is a useful feature to be considered.
Thanks,
Qi

**Comment by monperrus** [comment]
PR accepted. Thanks.
