### ISSUE TITLE
Add user-friendly interface for easier bibtex entries management

### ISSUE THREAD

**Issue by i2000s** [monperrus/bibtexbrowser#64]
Hi Martin,

I was thinking of making a GUI for non-expert people to easily edit the bibtex file and add new bibtex entries on their web browser using your bibtexbrowser tool. I thought I can just use any file mangement plugins to edit the bib file, but these plugins are designed to edit any files on the server and are dangerous to grant people such a permission power. Could you think about making an interface for users to edit and solely edit the bibtex entries without going into the administration backend? If you have any concrete idea to implement this feature, I would also be interested to try out as long as it is not beyond my limited knowledge of php.

I have noticed that you are working on the command line interface for bibtexbrowser. It might be easy for your to implement this feature next.

Thanks,
Qi

**Comment by monperrus** [comment]
Thanks for the suggestion, yet I don't have any plan to work on this in a near future?
