### ISSUE TITLE
Align the CSS classes of JanosBibliographyStyle with the default ones

### ISSUE THREAD

**Issue by ManiShiyam** [monperrus/bibtexbrowser#72]
I am able to change the fontsize etc via custom css in wordpress. But when I change the style to 'JanosBibliographyStyle' I am no longer able to customize the view (fontsize, etc.)

**Comment by monperrus** [comment]
The reason is that JanosBibliographyStyle probably doesn't contain the same CSS classes as the
default style.

This can be considered a bug. Would you make a pull request to fix this?

Thanks.
