### ISSUE TITLE
Fatal error: require(): Failed opening required 'reflectivedoc.php

### ISSUE THREAD

**Issue by DimitriRU** [monperrus/bibtexbrowser#79]
I am try to install it on xampp but i got an error like:

> Warning: Class '\PHPUnit\Framework\TestCase' not found in C:\xampp\htdocs\bib\bibtexbrowser-test.php on line 17
> 
> Fatal error: require(): Failed opening required 'reflectivedoc.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\bib\bibtexbrowser-test.php on line 40

To fix first error i used
`require_once 'PHPUnit/Autoload.php';`

But i do not know how to fix second "Fatal error".

PHP Version 7.1.12

**Comment by monperrus** [comment]
See test script in .travis.yml:

> curl -L -o reflectivedoc.php 
> https://www.monperrus.net/martin/reflectivedoc.php.txt
>
> curl -L -o gakowiki-syntax.php 
> https://www.monperrus.net/martin/gakowiki-syntax.php.txt
