### ISSUE TITLE
Use default bib-file specified by constant

### ISSUE THREAD

**Issue by fabianfaul** [monperrus/bibtexbrowser#93]
First of all, thanks for this application!

I'd like to use bibtexbrowser to display a bib-file that is updated from time to time. Since I want to access the bibtexbrowser directly by a domain (e.g. bibtex.example.org), I cannot pass any GET-parameter. Therefore, it would be helpful if the bib-file could be also specified by a constant.
I would be happy to implement this but was not sure where the bib-file is specified. Is it always called from the GET-variable or is there a specific variable where the filename is stored?

Thanks,
Fabian

**Comment by monperrus** [comment]
Create a file `bibtexbrowser.local.php`, and there you add 

```
<?php
$_GET['bib']='defaultfile.bib';
?>
```

Works for you?

**Comment by fabianfaul** [comment]
Good idea, thanks.. And indeed, it works but only if the variable is set directly in the `bibtexbrowser.php`.
